#Confgiuração do arquivo 00-installer-config.yaml 
#diretório /etc/netplan

#Cuidar, pois este arquivo de configuração precisa estar
#bem alinhado os espaços para não dar erro.
#não é permitido tabulações no arquivo

network:
  ethernets:
    enp9s0:
      dhcp4: true
    ens6f0:
      dhcp4: false
      addresses:
       - 172.16.1.82/24
      routes:
        - to: default
          via: 172.16.1.1
          metric: 100
      nameservers:
       search: [home]
       addresses: [8.8.8.8, 8.8.4.4]
    ens6f1:
      dhcp4: true
  version: 2


#enp3s4f0: Modificar para sua rede
#addresses: 
#- ***.***.***.***/** modificar para seu endereço de rede
#gateway4: ***.**.*.* modificar para seu gateway(rota estática)
#nameservers:
#search: [home]
#addresses: [***.**.*.*, 8.8.8.8] endereço de gateway da sua rede e adicionei o do google ao lado, 
#lembrando que neste arquivo precisa estar separado com ","

###"ip rout s" você mostra os endereços de rota estática(gateway)disponiveis para sua rede###


#Após a configuração do resolved.conf, aplicar as configurações
#digitando o comando: "netplan apply" (aplicar as configurações do arq "#00-")
#Caso ocorra algum erro após o "netplan apply", volte ao arquivo e olhe os espaçametos antes das informações.
#Após isto, digite o comando: "systemctl restart systemd-resolved" (aplicar as configurações DNS do resolved)
